### ISSUE TITLE
[Feature request] Convert this script into a Cura Postprocessing Script

### ISSUE THREAD

**Issue by 5axes** [CNCKitchen/GradientInfill#9]
Could be interesting to convert this script into a Cura Postprocessing script to test the potential of this new infill method without running the script from a Python IDE  and necessity to modify the File Input and Output name.

**Comment by Sazoji** [comment]
it would be _very_ easy to do with a few script changes https://github.com/Ultimaker/Cura/tree/master/plugins/PostProcessingPlugin/scripts
python is already used as the post processing script language

**Comment by 5axes** [comment]
I know it ...   That's why I've done it :)  a Pull Request will follow in a short delay after some modifications . I need to test the script then symplify the parameter list, as you can have directly access in the Cura parameter list to the profile settings . So check if we have  a LINEAR or SMALL_SEGMENTS style infill pattern, check if we are in the relativ mode and so on.
